version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: assist_ai_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Letmein
      POSTGRES_DB: assist_ai_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: assist_ai_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@assist.ai
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db

volumes:
  postgres_data: